package io.github.nbcss.xengine.api;

import io.github.nbcss.xengine.core.MapColor;
import net.minecraft.world.level.material.MaterialColor;

public interface XMapColor {
    XMapColor CLEAR = new MapColor(MaterialColor.NONE);
    XMapColor PALE_GREEN = new MapColor(MaterialColor.GRASS);
    XMapColor PALE_YELLOW = new MapColor(MaterialColor.SAND);
    XMapColor WHITE_GRAY = new MapColor(MaterialColor.WOOL);
    XMapColor BRIGHT_RED = new MapColor(MaterialColor.FIRE);
    XMapColor PALE_PURPLE = new MapColor(MaterialColor.ICE);
    XMapColor IRON_GRAY = new MapColor(MaterialColor.METAL);
    XMapColor DARK_GREEN = new MapColor(MaterialColor.PLANT);
    XMapColor WHITE = new MapColor(MaterialColor.SNOW);
    XMapColor LIGHT_BLUE_GRAY = new MapColor(MaterialColor.CLAY);
    XMapColor DIRT_BROWN = new MapColor(MaterialColor.DIRT);
    XMapColor STONE_GRAY = new MapColor(MaterialColor.STONE);
    XMapColor WATER_BLUE = new MapColor(MaterialColor.WATER);
    XMapColor OAK_TAN = new MapColor(MaterialColor.WOOD);
    XMapColor OFF_WHITE = new MapColor(MaterialColor.QUARTZ);
    XMapColor ORANGE = new MapColor(MaterialColor.COLOR_ORANGE);
    XMapColor MAGENTA = new MapColor(MaterialColor.COLOR_MAGENTA);
    XMapColor LIGHT_BLUE = new MapColor(MaterialColor.COLOR_LIGHT_BLUE);
    XMapColor YELLOW = new MapColor(MaterialColor.COLOR_YELLOW);
    XMapColor LIME = new MapColor(MaterialColor.COLOR_LIGHT_GREEN);
    XMapColor PINK = new MapColor(MaterialColor.COLOR_PINK);
    XMapColor GRAY = new MapColor(MaterialColor.COLOR_GRAY);
    XMapColor LIGHT_GRAY = new MapColor(MaterialColor.COLOR_LIGHT_GRAY);
    XMapColor CYAN = new MapColor(MaterialColor.COLOR_CYAN);
    XMapColor PURPLE = new MapColor(MaterialColor.COLOR_PURPLE);
    XMapColor BLUE = new MapColor(MaterialColor.COLOR_BLUE);
    XMapColor BROWN = new MapColor(MaterialColor.COLOR_BROWN);
    XMapColor GREEN = new MapColor(MaterialColor.COLOR_GREEN);
    XMapColor RED = new MapColor(MaterialColor.COLOR_RED);
    XMapColor BLACK = new MapColor(MaterialColor.COLOR_BLACK);
    XMapColor GOLD = new MapColor(MaterialColor.GOLD);
    XMapColor DIAMOND_BLUE = new MapColor(MaterialColor.DIAMOND);
    XMapColor LAPIS_BLUE = new MapColor(MaterialColor.LAPIS);
    XMapColor EMERALD_GREEN = new MapColor(MaterialColor.EMERALD);
    XMapColor SPRUCE_BROWN = new MapColor(MaterialColor.PODZOL);
    XMapColor DARK_RED = new MapColor(MaterialColor.NETHER);
    XMapColor TERRACOTTA_WHITE = new MapColor(MaterialColor.TERRACOTTA_WHITE);
    XMapColor TERRACOTTA_ORANGE = new MapColor(MaterialColor.TERRACOTTA_ORANGE);
    XMapColor TERRACOTTA_MAGENTA = new MapColor(MaterialColor.TERRACOTTA_MAGENTA);
    XMapColor TERRACOTTA_LIGHT_BLUE = new MapColor(MaterialColor.TERRACOTTA_LIGHT_BLUE);
    XMapColor TERRACOTTA_YELLOW = new MapColor(MaterialColor.TERRACOTTA_YELLOW);
    XMapColor TERRACOTTA_LIME = new MapColor(MaterialColor.TERRACOTTA_LIGHT_GREEN);
    XMapColor TERRACOTTA_PINK = new MapColor(MaterialColor.TERRACOTTA_PINK);
    XMapColor TERRACOTTA_GRAY = new MapColor(MaterialColor.TERRACOTTA_GRAY);
    XMapColor TERRACOTTA_LIGHT_GRAY = new MapColor(MaterialColor.TERRACOTTA_LIGHT_GRAY);
    XMapColor TERRACOTTA_CYAN = new MapColor(MaterialColor.TERRACOTTA_CYAN);
    XMapColor TERRACOTTA_PURPLE = new MapColor(MaterialColor.TERRACOTTA_PURPLE);
    XMapColor TERRACOTTA_BLUE = new MapColor(MaterialColor.TERRACOTTA_BLUE);
    XMapColor TERRACOTTA_BROWN = new MapColor(MaterialColor.TERRACOTTA_BROWN);
    XMapColor TERRACOTTA_GREEN = new MapColor(MaterialColor.TERRACOTTA_GREEN);
    XMapColor TERRACOTTA_RED = new MapColor(MaterialColor.TERRACOTTA_RED);
    XMapColor TERRACOTTA_BLACK = new MapColor(MaterialColor.TERRACOTTA_BLACK);
    XMapColor DULL_RED = new MapColor(MaterialColor.CRIMSON_NYLIUM);
    XMapColor DULL_PINK = new MapColor(MaterialColor.CRIMSON_STEM);
    XMapColor DARK_CRIMSON = new MapColor(MaterialColor.CRIMSON_HYPHAE);
    XMapColor TEAL = new MapColor(MaterialColor.WARPED_NYLIUM);
    XMapColor DARK_AQUA = new MapColor(MaterialColor.WARPED_STEM);
    XMapColor DARK_DULL_PINK = new MapColor(MaterialColor.WARPED_HYPHAE);
    XMapColor BRIGHT_TEAL = new MapColor(MaterialColor.WARPED_WART_BLOCK);
    XMapColor DEEPSLATE_GRAY = new MapColor(MaterialColor.DEEPSLATE);
    XMapColor RAW_IRON_PINK = new MapColor(MaterialColor.RAW_IRON);
    XMapColor LICHEN_GREEN = new MapColor(MaterialColor.GLOW_LICHEN);
}
