package io.github.nbcss.xengine.api;

import io.github.nbcss.xengine.core.MapColor;
import net.minecraft.world.level.material.MaterialMapColor;

public interface XMapColor {
    XMapColor CLEAR = new MapColor(MaterialMapColor.b);
    XMapColor PALE_GREEN = new MapColor(MaterialMapColor.c);
    XMapColor PALE_YELLOW = new MapColor(MaterialMapColor.d);
    XMapColor WHITE_GRAY = new MapColor(MaterialMapColor.e);
    XMapColor BRIGHT_RED = new MapColor(MaterialMapColor.f);
    XMapColor PALE_PURPLE = new MapColor(MaterialMapColor.g);
    XMapColor IRON_GRAY = new MapColor(MaterialMapColor.h);
    XMapColor DARK_GREEN = new MapColor(MaterialMapColor.i);
    XMapColor WHITE = new MapColor(MaterialMapColor.j);
    XMapColor LIGHT_BLUE_GRAY = new MapColor(MaterialMapColor.k);
    XMapColor DIRT_BROWN = new MapColor(MaterialMapColor.l);
    XMapColor STONE_GRAY = new MapColor(MaterialMapColor.m);
    XMapColor WATER_BLUE = new MapColor(MaterialMapColor.n);
    XMapColor OAK_TAN = new MapColor(MaterialMapColor.o);
    XMapColor OFF_WHITE = new MapColor(MaterialMapColor.p);
    XMapColor ORANGE = new MapColor(MaterialMapColor.q);
    XMapColor MAGENTA = new MapColor(MaterialMapColor.r);
    XMapColor LIGHT_BLUE = new MapColor(MaterialMapColor.s);
    XMapColor YELLOW = new MapColor(MaterialMapColor.t);
    XMapColor LIME = new MapColor(MaterialMapColor.u);
    XMapColor PINK = new MapColor(MaterialMapColor.v);
    XMapColor GRAY = new MapColor(MaterialMapColor.w);
    XMapColor LIGHT_GRAY = new MapColor(MaterialMapColor.x);
    XMapColor CYAN = new MapColor(MaterialMapColor.y);
    XMapColor PURPLE = new MapColor(MaterialMapColor.z);
    XMapColor BLUE = new MapColor(MaterialMapColor.A);
    XMapColor BROWN = new MapColor(MaterialMapColor.B);
    XMapColor GREEN = new MapColor(MaterialMapColor.C);
    XMapColor RED = new MapColor(MaterialMapColor.D);
    XMapColor BLACK = new MapColor(MaterialMapColor.E);
    XMapColor GOLD = new MapColor(MaterialMapColor.F);
    XMapColor DIAMOND_BLUE = new MapColor(MaterialMapColor.G);
    XMapColor LAPIS_BLUE = new MapColor(MaterialMapColor.H);
    XMapColor EMERALD_GREEN = new MapColor(MaterialMapColor.I);
    XMapColor SPRUCE_BROWN = new MapColor(MaterialMapColor.J);
    XMapColor DARK_RED = new MapColor(MaterialMapColor.K);
    XMapColor TERRACOTTA_WHITE = new MapColor(MaterialMapColor.L);
    XMapColor TERRACOTTA_ORANGE = new MapColor(MaterialMapColor.M);
    XMapColor TERRACOTTA_MAGENTA = new MapColor(MaterialMapColor.N);
    XMapColor TERRACOTTA_LIGHT_BLUE = new MapColor(MaterialMapColor.O);
    XMapColor TERRACOTTA_YELLOW = new MapColor(MaterialMapColor.P);
    XMapColor TERRACOTTA_LIME = new MapColor(MaterialMapColor.Q);
    XMapColor TERRACOTTA_PINK = new MapColor(MaterialMapColor.R);
    XMapColor TERRACOTTA_GRAY = new MapColor(MaterialMapColor.S);
    XMapColor TERRACOTTA_LIGHT_GRAY = new MapColor(MaterialMapColor.T);
    XMapColor TERRACOTTA_CYAN = new MapColor(MaterialMapColor.U);
    XMapColor TERRACOTTA_PURPLE = new MapColor(MaterialMapColor.V);
    XMapColor TERRACOTTA_BLUE = new MapColor(MaterialMapColor.W);
    XMapColor TERRACOTTA_BROWN = new MapColor(MaterialMapColor.X);
    XMapColor TERRACOTTA_GREEN = new MapColor(MaterialMapColor.Y);
    XMapColor TERRACOTTA_RED = new MapColor(MaterialMapColor.Z);
    XMapColor TERRACOTTA_BLACK = new MapColor(MaterialMapColor.aa);
    XMapColor DULL_RED = new MapColor(MaterialMapColor.ab);
    XMapColor DULL_PINK = new MapColor(MaterialMapColor.ac);
    XMapColor DARK_CRIMSON = new MapColor(MaterialMapColor.ad);
    XMapColor TEAL = new MapColor(MaterialMapColor.ae);
    XMapColor DARK_AQUA = new MapColor(MaterialMapColor.af);
    XMapColor DARK_DULL_PINK = new MapColor(MaterialMapColor.ag);
    XMapColor BRIGHT_TEAL = new MapColor(MaterialMapColor.ah);
    XMapColor DEEPSLATE_GRAY = new MapColor(MaterialMapColor.ai);
    XMapColor RAW_IRON_PINK = new MapColor(MaterialMapColor.aj);
    XMapColor LICHEN_GREEN = new MapColor(MaterialMapColor.ak);
}
