package io.github.nbcss.xengine.api.block;

import io.github.nbcss.xengine.core.block.BlockMaterial;
import net.minecraft.world.level.material.Material;

public interface XBlockMaterial {
    XBlockMaterial AIR = new BlockMaterial(Material.AIR);
    XBlockMaterial STRUCTURE_VOID = new BlockMaterial(Material.STRUCTURAL_AIR);
    XBlockMaterial PORTAL = new BlockMaterial(Material.PORTAL);
    XBlockMaterial CARPET = new BlockMaterial(Material.CLOTH_DECORATION);
    XBlockMaterial PLANT = new BlockMaterial(Material.PLANT);
    XBlockMaterial UNDERWATER_PLANT = new BlockMaterial(Material.WATER_PLANT);
    XBlockMaterial REPLACEABLE_PLANT = new BlockMaterial(Material.REPLACEABLE_PLANT);
    XBlockMaterial NETHER_SHOOTS = new BlockMaterial(Material.REPLACEABLE_FIREPROOF_PLANT);
    XBlockMaterial REPLACEABLE_UNDERWATER_PLANT = new BlockMaterial(Material.REPLACEABLE_WATER_PLANT);
    XBlockMaterial WATER = new BlockMaterial(Material.WATER);
    XBlockMaterial BUBBLE_COLUMN = new BlockMaterial(Material.BUBBLE_COLUMN);
    XBlockMaterial LAVA = new BlockMaterial(Material.LAVA);
    XBlockMaterial SNOW_LAYER = new BlockMaterial(Material.TOP_SNOW);
    XBlockMaterial FIRE = new BlockMaterial(Material.FIRE);
    XBlockMaterial DECORATION = new BlockMaterial(Material.DECORATION);
    XBlockMaterial COBWEB = new BlockMaterial(Material.WEB);
    XBlockMaterial SCULK = new BlockMaterial(Material.SCULK);
    XBlockMaterial REDSTONE_LAMP = new BlockMaterial(Material.BUILDABLE_GLASS);
    XBlockMaterial ORGANIC_PRODUCT = new BlockMaterial(Material.CLAY);
    XBlockMaterial SOIL = new BlockMaterial(Material.DIRT);
    XBlockMaterial SOLID_ORGANIC = new BlockMaterial(Material.GRASS);
    XBlockMaterial DENSE_ICE = new BlockMaterial(Material.ICE_SOLID);
    XBlockMaterial AGGREGATE = new BlockMaterial(Material.SAND);
    XBlockMaterial SPONGE = new BlockMaterial(Material.SPONGE);
    XBlockMaterial SHULKER_BOX = new BlockMaterial(Material.SHULKER_SHELL);
    XBlockMaterial WOOD = new BlockMaterial(Material.WOOD);
    XBlockMaterial NETHER_WOOD = new BlockMaterial(Material.NETHER_WOOD);
    XBlockMaterial BAMBOO_SAPLING = new BlockMaterial(Material.BAMBOO_SAPLING);
    XBlockMaterial BAMBOO = new BlockMaterial(Material.BAMBOO);
    XBlockMaterial WOOL = new BlockMaterial(Material.WOOL);
    XBlockMaterial TNT = new BlockMaterial(Material.EXPLOSIVE);
    XBlockMaterial LEAVES = new BlockMaterial(Material.LEAVES);
    XBlockMaterial GLASS = new BlockMaterial(Material.GLASS);
    XBlockMaterial ICE = new BlockMaterial(Material.ICE);
    XBlockMaterial CACTUS = new BlockMaterial(Material.CACTUS);
    XBlockMaterial STONE = new BlockMaterial(Material.STONE);
    XBlockMaterial METAL = new BlockMaterial(Material.METAL);
    XBlockMaterial SNOW_BLOCK = new BlockMaterial(Material.SNOW);
    XBlockMaterial REPAIR_STATION = new BlockMaterial(Material.HEAVY_METAL);
    XBlockMaterial BARRIER = new BlockMaterial(Material.BARRIER);
    XBlockMaterial PISTON = new BlockMaterial(Material.PISTON);
    XBlockMaterial MOSS_BLOCK = new BlockMaterial(Material.MOSS);
    XBlockMaterial GOURD = new BlockMaterial(Material.VEGETABLE);
    XBlockMaterial EGG = new BlockMaterial(Material.EGG);
    XBlockMaterial CAKE = new BlockMaterial(Material.CAKE);
    XBlockMaterial AMETHYST = new BlockMaterial(Material.AMETHYST);
    XBlockMaterial POWDER_SNOW = new BlockMaterial(Material.POWDER_SNOW);
}
